export enum ErrorType {
  GENERAL = 'GENERAL',
  NETWORK = 'NETWORK',
  TIMEOUT = 'TIMEOUT',
  SERVER = 'SERVER',
  NONE = 'NONE',
  MANUAL_HANDLER = 'MANUAL_HANDLER'
}

export enum InputType {
  EMAIL = 'EMAIL',
  PHONE_NUMBER = "PHONE_NUMBER",
  PASSWORD = "PASSWORD",
  CONFIRM_PASSWORD = "CONFIRM_PASSWORD",
  GENERAL = 'GENERAL',
  FIRST_NAME = 'FIRST_NAME',
  LAST_NAME = 'LAST_NAME',
  HEIGHT = 'HEIGHT',
  WEIGHT = 'WEIGHT',
  ALPHA_NUMERIC = 'ALPHA_NUMERIC',
  DIGIT_CODE = 'DIGIT_CODE'
}